name: Snake Action

on:
  push:
    branches:
      - main
  schedule:
    # every 6 hours
      - cron: "0 */6 * * *"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v3.0.0
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
